from tkinter import *
class register:
    def __init__(self):
        self.root=Tk()
        self.root.title("LOGIN PAGE")
        self.root.geometry("800x900")
        self.root.config(bg="#0A457D")
        self.root.resizable(False,False)
        self.frame=Frame(self.root,bg="white",width=400,height=400)
        self.frame.place(x=200,y=100)
        self.label1=Label(self.root,text="Card Payment",bg="#0A457D",fg="yellow",font=("Times New Roman",40,"bold"))
        self.label1.place(x=230,y=30)
        self.label1=Label(self.root,text="   Name On Card :  ",bg="white",fg="black",font=("Bodoni MT",20,"bold"))
        self.label1.place(x=200,y=120)
        self.entry1=Entry(self.root,bg="#c8cacb",fg="black",font=("Bodoni MT",20,"bold"))
        self.entry1.place(x=220,y=160)
        self.label2=Label(self.root,text="  Card Number :  ",bg="white",fg="black",font=("Bodoni MT",20,"bold"))
        self.label2.place(x=200,y=200)
        self.entry2=Entry(self.root,bg="#c8cacb",fg="black",font=("Bodoni MT",20,"bold"))
        self.entry2.place(x=220,y=240)
        self.label3=Label(self.root,text="  Expiration date(dd/mm/yyyy) :  ",bg="white",fg="black",font=("Bodoni MT",20,"bold"))
        self.label3.place(x=200,y=280)
        self.entry3=Entry(self.root,bg="#c8cacb",fg="black",font=("Bodoni MT",20,"bold"))
        self.entry3.place(x=220,y=320)
        self.label4=Label(self.root,text="  CVV :  ",bg="white",fg="black",font=("Bodoni MT",20,"bold"))
        self.label4.place(x=200,y=360)
        self.entry4=Entry(self.root,bg="#c8cacb",fg="black",font=("Bodoni MT",20,"bold"))
        self.entry4.place(x=220,y=400)
        self.button1=Button(self.root,text="         Pay Now         ",bg="#0E6C9C",fg="white",font=("Arial",20,"bold"),command=self.show)
        self.button1.place(x=250,y=440)
        self.root.mainloop()
    def show(self):
     print(self.entry1.get())
     print(self.entry2.get())
     print(self.entry3.get())
     print(self.entry4.get())
obj=register()
