import tkinter as tk
root=tk.Tk()
root.title("My first GUI Program")
root.geometry("800x600")
root.resizable(False,False)
root.config(bg="grey")
label=tk.Label(root,text="REGISTRATION PAGE",bg="red",fg="black",font=("Times New Roman",35,"bold"))
label.place(x=140,y=25)
label1=tk.Label(root,text="Enter Name:",bg="white",fg="black",font=("Arial",20,"bold"))
label1.place(x=50,y=100)
enter1=tk.Entry(root,bg="white",fg="black",font=("Arial",20,"bold"))
enter1.place(x=250,y=100)
label2=tk.Label(root,text="Enter age:",bg="white",fg="black",font=("Arial",20,"bold"))
label2.place(x=50,y=150)
enter2=tk.Entry(root,bg="white",fg="black",font=("Arial",20,"bold"))
enter2.place(x=250,y=150)
label3=tk.Label(root,text="Enter mail id:",bg="white",fg="black",font=("Arial",20,"bold"))
label3.place(x=50,y=200)
enter3=tk.Entry(root,bg="white",fg="black",font=("Arial",20,"bold"))
enter3.place(x=250,y=200)
label4=tk.Label(root,text="Enter password:",bg="white",fg="black",font=("Arial",20,"bold"))
label4.place(x=50,y=250)
enter4=tk.Entry(root,show="*",bg="white",fg="black",font=("Arial",20,"bold"))
enter4.place(x=300,y=250)
button1=tk.Button(root,text="Submit",bg="green",fg="white",font=("Arial",30,"bold"),command=lambda:show())
button1.place(x=250,y=300)
def show():
    print(enter1.get())
    print(enter2.get())
    print(enter3.get())
    print(enter4.get())
root.mainloop()