a="hello world"
print(len(a))
a="my name is anthony Gonzales"
# print(a[4:9:1])
# print(a[2:13:1])
# print(a[14:2:1])
# print(a[2:13:2])
# print(a[::2])
# print(a[::-1])
# print(a[3:30:3])
# print(a.title())
# print(a.upper())
# print(a.swapcase())
# print(a.startswith("ms"))
# print(a.replace("anthony gonzales","MUSKAN"))
# print(a.split("n"))
# print(a.rfind("a"))
# print(a.endswith("s"))
# print(a.index("y"))
# print(a.split("i"))
# print(a.startswith("m"))
print(a.isupper())